import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GetServerSideProps } from "next";
// import Layout from "./components/layout";
// import { usePathname, useSearchParams } from 'next/navigation';
import { headers } from 'next/headers';

interface PageProps {
  rootUrl: string;
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCurrentPathname() {
  const headersList = await headers();
  const referer = headersList.get('referer');
  // const pathname = new URL(headersList.get('referer')).pathname;
  const pathname = referer ? new URL(referer).pathname : '/';
  return pathname;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const pathname = usePathname(); 
  const pathname =  await getCurrentPathname();
  const isAdminPage = pathname.startsWith('/dashboard');
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div><h1>Current URL: {pathname}</h1></div>
        {children}
      </body>
    </html>
  );
}
